### ISSUE TITLE
NginxPushStreamBundle

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [cmosguy/laravel-http-pushstream-broadcaster#10]
I wrote a similar package (for Symfony2) almost 2 years ago and it still has some advantages e.g.:
1. filters for namespacing channel names (using prefixes) and for obscuring channel names from other users.
2. id generators which are the must for polling and long polling strategies in order to not lose messages.
3. flexible configuration, template urls.
So you may want to take a look.
https://github.com/AlexeyKupershtokh/nginx_push_stream_bundle

**Comment by cmosguy** [comment]
@AlexeyKupershtokh thanks for the heads up here.  I'll take a look at this!
