### ISSUE TITLE
Class 'Cmosguy\Broadcasting\PushStreamBroadcastManagerProvider' not found

### ISSUE THREAD

**Issue by easmith** [cmosguy/laravel-http-pushstream-broadcaster#3]
```
 Class 'Cmosguy\Broadcasting\PushStreamBroadcastManagerProvider' not found
```

Why? I did everything according to instructions. Composer -> insert provider line -> test

**Comment by easmith** [comment]
Work with 

```
"cmosguy/laravel-http-pushstream-broadcaster": "dev-master"
```

Please commit ccurrent version to packagist

**Comment by cmosguy** [comment]
@easmith sorry i missed the boat on your latest issue here.  Are you able to get what you need with you latest merged pull request on the dev-master in packagist?.  Can we close this issue?

**Comment by fer-ri** [comment]
We need to use `dev-master` since there''s change about `autoload` section in composer.json

**Comment by kohenkatz** [comment]
:+1: Please release `0.3.0` (or similar) to publish the fix for fix the `composer.json` autoload issue.

**Comment by cmosguy** [comment]
Hey @easmith  and @kohenkatz I have updated the tags for the latest version here.  https://github.com/cmosguy/laravel-http-pushstream-broadcaster/tree/0.3

Thanks for comments!
